services:
  web:
    image: bohdaninhliziian/fastapi:latest
    container_name: web
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
