version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"

  nginx:
      restart: unless-stopped
      image: nginx
      container_name: nginx
      ports:
        - "80:80"
        # - "443:443"
      # environment:
      #   - CERTBOT_EMAIL=youremail@gmail.com
      volumes:
        - ./nginx:/etc/nginx/user_conf.d:ro
        # - letsencrypt:/etc/letsencrypt
      depends_on:
        - app
      logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "1"